name: build-bigpod

on:
  schedule:
    - cron: '40 22 * * *'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.txt'
  workflow_dispatch:
      
      
env:
  IMAGE_NAME: ubuntu
  IMAGE_REGISTRY: ghcr.io/bigpodsb

jobs: 
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        image_flavor: [main, nvidia]
        major_version: [38, 39]
        #exclude: 
        #  - image_flavor: nvidia
        #    major_version: 38
    steps:
    - name: Checkout Push to Registry action
      uses: actions/checkout@v3
    - name: apt rm
      run: sudo apt autoremove -y adwaita-icon-theme aria2 azure-cli byobu dotnet-sdk-6.0 dotnet-sdk-7.0 dotnet-runtime-7.0 dotnet-runtime-6.0 docker-ce htop p7zip-full p7zip-rar postgresql-14 r-base-core r-base-dev r-base wget x11-common gcc-9 gcc-10 gcc-11 gcc-12 gcc-13 g++-9 g++-10 g++-11 g++-12 g++-13 gfortran-9 gfortran-10 gfortran-11 gfortran-12 google-chrome-stable google-cloud-sdk hicolor-icon-theme humanity-icon-theme hunspell-en-us java-common javascript-common microsoft-edge-stable mono-runtime-common mysql-server mysql-client nginx php-common powershell rpm rpm2cpio ruby-full snapd zip apache2-bin bison bzip2 clang-12 clang-13 clang-14 clang-15 cron cpp-11 docker-ce-cli docker-buildx-plugin gcc-11-base gcc-12-base landscape-common llvm-12 llvm-13 llvm-14 llvm-15 mssql-tools mysql-common postgresql-client-common postgresql-client-14 python-is-python3 python3 ruby-dev ruby 
      shell: bash
    - name: build
      shell: bash
      run: podman build . -t buildoutput:latest --build-arg IMAGE_TYPE=$(./checks.sh ${{ matrix.image_flavor }}) --build-arg FEDORA_MAJOR_VERSION=${{ matrix.major_version }}
    - name: tag
      shell: bash
      run: |
        podman tag buildoutput:latest ghcr.io/bigpod98/bigpodsb/alpha-${{ matrix.image_flavor }}:${{ matrix.major_version }}
    - name: login
      shell: bash
      run: podman login ghcr.io -u bigpod98 -p ${{ secrets.GITHUB_TOKEN }}
    - name: push
      shell: bash
      run: podman push ghcr.io/bigpod98/bigpodsb/alpha-${{ matrix.image_flavor }}:${{ matrix.major_version }}
    - name: test
      shell: bash
      run: df -h && free -h    
