name: build-bigpod

on:
  schedule:
    - cron: '12 00 * * *'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.txt'
  workflow_dispatch:
      
      
env:
  IMAGE_NAME: ubuntu
  IMAGE_REGISTRY: ghcr.io/bigpod98

jobs: 
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        image_flavor: [main, nvidia]
        major_version: [37]
        include:
          - major_version: 37
            is_latest_version: true
            is_stable_version: true
 #        - major_version: 38
 #          is_latest_version: false
 #          is_stable_version: false
    steps:
    - name: Checkout Push to Registry action
      uses: actions/checkout@v3
    - name: check
      shell: bash
      run: echo ${./checks.sh ${{ matrix.image_flavor }}}
    - name: build
      shell: bash
      run: podman build . -t buildoutput:latest -build-arg --build-arg IMAGE_TYPE=${./checks.sh ${{ matrix.image_flavor }}} --build-arg FEDORA_MAJOR_VERSION=${{ matrix.major_version }}
    - name: tag
      shell: bash
      run: |
        podman tag buildoutput:latest ghcr.io/bigpod98/bigpodsb/alpha-${{ matrix.image_flavor }}:"${{ matrix.major_version }}
    - name: login
      shell: bash
      run: podman login ghcr.io -u bigpod98 -p ${{ secrets.GITHUB_TOKEN }}
    - name: push
      shell: bash
      run: podman push ghcr.io/bigpod98/bigpodsb/alpha-${{ matrix.image_flavor }}:"${{ matrix.major_version }}
      
