name: build-bigpod

on:
  schedule:
    - cron: '40 22 * * *'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.txt'
  workflow_dispatch:
      
      
env:
  IMAGE_NAME: ubuntu
  IMAGE_REGISTRY: ghcr.io/bigpodsb

jobs: 
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        image_flavor: [main, nvidia]
        major_version: [39]
        #exclude: 
        #  - image_flavor: nvidia
        #    major_version: 38
    steps:
    - name: size available before
      shell: bash
      run: | 
            df -h  &&
            sudo docker image prune --all --force &&
            sudo podman image prune --all --force &&
            podman image prune --all --force &&
            sudo rm -rf /opt/hostedtoolcache/CodeQL &&
            sudo rm -rf /usr/local/share/boost &&
            sudo rm -rf $AGENT_TOOLSDIRECTORY &&
            sudo rm -rf /opt/ghc &&
            sudo rm -rf /var/cache/apt &&
            sudo rm -rf /usr/share/dotnet &&
            sudo rm -rf /usr/local/lib/android &&
            df -h
    - name: Checkout Push to Registry action
      uses: actions/checkout@v3
    - name: build
      shell: bash
      run: podman build . -t buildoutput:latest --build-arg IMAGE_TYPE=$(./checks.sh ${{ matrix.image_flavor }}) --build-arg FEDORA_MAJOR_VERSION=${{ matrix.major_version }}
    - name: tag
      shell: bash
      run: |
        podman tag buildoutput:latest ghcr.io/bigpod98/bigpodsb/alpha-${{ matrix.image_flavor }}:${{ matrix.major_version }}
    - name: login
      shell: bash
      run: podman login ghcr.io -u bigpod98 -p ${{ secrets.GITHUB_TOKEN }}
    - name: push
      shell: bash
      run: podman push ghcr.io/bigpod98/bigpodsb/alpha-${{ matrix.image_flavor }}:${{ matrix.major_version }}
    - name: test
      shell: bash
      run: df -h && free -h    
