name: build-bigpod

on:
  schedule:
    - cron: '40 22 * * *'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.txt'
  workflow_dispatch:
      
      
env:
  IMAGE_NAME: ubuntu
  IMAGE_REGISTRY: ghcr.io/bigpod98

jobs: 
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        image_flavor: [main]
        major_version: [37]
    steps:
    - name: Checkout Push to Registry action
      uses: actions/checkout@v3
    - name: build
      shell: bash
      run: podman build . -t buildoutput:latest --build-arg IMAGE_TYPE=$(./checks.sh ${{ matrix.image_flavor }}) --build-arg FEDORA_MAJOR_VERSION=${{ matrix.major_version }} --cap-add=ALL
    - name: tag
      shell: bash
      run: |
        podman tag buildoutput:latest ghcr.io/bigpod98/bigpodsb/alpha-flatpak:${{ matrix.major_version }}
    - name: login
      shell: bash
      run: podman login ghcr.io -u bigpod98 -p ${{ secrets.GITHUB_TOKEN }}
    - name: push
      shell: bash
      run: podman push ghcr.io/bigpod98/bigpodsb/alpha-flatpak:${{ matrix.major_version }}
      
